version: '2.1'

services:
  # Node 1
  db:
      image: postgres:9.5-alpine
      restart: always
      environment:
        POSTGRES_PASSWORD: '123456'
        PGDATA: '/var/lib/postgresql/data/pgdata'
      volumes:
        - ./data/db1:/var/lib/postgresql/data
      ports:
        - 55432:5432

  redis:
      image: redis
      environment:
        - ALLOW_EMPTY_PASSWORD=yes
      ports:
        - 56379:6379

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: SuperSecr3t
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - ./data/rabbitmq1:/var/lib/rabbitmq

    # dev:
    #   image: golang:latest
    #   ports:
    #     - 8080:8080
    #   volumes:
    #       - ./config:/opt/loyalty/etc/
    #       - ./:/app
      # command: "go run /app/server/main.go api"
